### ISSUE TITLE
node vs pull stream benchmark results?

### ISSUE THREAD

**Issue by ahdinosaur** [yoshuawuyts/playground-pull-stream#1]
hey @yoshuawuyts, just wondering, how do you feel these benchmarks using pull streams compare to [a similar benchmark you did using node streams](https://github.com/yoshuawuyts/playground-http-bench)?

part of me is worried pull streams are slow because it necessitates closures, which seem to be thought of as slower than constructors with prototype methods and `this`.

i'm curious as i'm starting to play with pull streams in an art project (controlling APA102 LEDs with a BeagleBone Black), as i think it's a better mental model (and much simpler code), because i might try to do more pull streams in professional projects, so am interested in how performance varies in relation to other stream implementations.

/cc @dominictarr

**Comment by yoshuawuyts** [comment]
so I had a lil chat to Hugh earlier today; and v8 can apparently optimize closures as long as they have the same type signature - most of the time. pull-streams might be on the fringe of optimizable; whereas node streams def are. On the other hand, Node streams have wayyy more internal complexity than pull-streams, which doesn't work in their favor.

Let's see if we can do a lil per test - I'll update the last example I had in the bench repo with the new `http-ndjson` package, and see how it stacks up against the latest pull-streams one (': I suspect it'll be close

**Comment by yoshuawuyts** [comment]
# node streams

``` txt
~/src/yw/playground-http-bench master
❯ wrk -c 400 -d 30 -t 12 http://localhost:1337
Running 30s test @ http://localhost:1337
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   303.99ms   72.23ms 938.84ms   90.77%
    Req/Sec    65.34     50.28   320.00     73.62%
  22824 requests in 30.10s, 6.31MB read
  Socket errors: connect 157, read 195, write 4, timeout 0
Requests/sec:    758.18
Transfer/sec:    214.72KB
```

**Comment by yoshuawuyts** [comment]
# pull streams

``` txt
❯ wrk -c 400 -d 30 -t 12 http://localhost:1337
Running 30s test @ http://localhost:1337
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   330.78ms   60.35ms 858.03ms   85.61%
    Req/Sec    64.13     51.47   313.00     73.38%
  21308 requests in 30.10s, 6.50MB read
  Socket errors: connect 157, read 179, write 0, timeout 0
Requests/sec:    707.83
Transfer/sec:    221.22KB
```

**Comment by yoshuawuyts** [comment]
Ran both on a dying machine - seem pretty damn close hey. 64 vs 65 `req/sec`

**Comment by yoshuawuyts** [comment]
Alright, found my power adapter. Here's the second run on a non-dying machine. Also noticed the `bankai` dep in pull-streams was a newer version, which sends more bytes over the wire; so updated to reflect that:

## node streams

``` txt
~/src/yw/playground-http-bench/full master*
❯ wrk -c 400 -d 30 -t 12 http://localhost:1337
Running 30s test @ http://localhost:1337
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    82.33ms   11.47ms 219.23ms   83.15%
    Req/Sec   289.91    173.05   666.00     55.27%
  86393 requests in 30.10s, 26.37MB read
  Socket errors: connect 157, read 148, write 0, timeout 0
Requests/sec:   2870.14
Transfer/sec:      0.88MB
```

## pull streams

``` txt
❯ wrk -c 400 -d 30 -t 12 http://localhost:1337
Running 30s test @ http://localhost:1337
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    85.84ms   12.71ms 292.50ms   88.60%
    Req/Sec   281.40    178.42   666.00     54.32%
  83475 requests in 30.09s, 25.47MB read
  Socket errors: connect 157, read 59, write 0, timeout 0
Requests/sec:   2774.25
Transfer/sec:    866.95KB
```

Apparently pull-streams operate on ~97% the speed of Node streams.

**Comment by yoshuawuyts** [comment]
hmm, but then again - maybe the above comparison isn't entirely reflective b/c we're [piping to `res`](https://github.com/yoshuawuyts/pull-http/blob/master/index.js#L52-L69) directly anyway; just have a bit of extra overhead. I think a JSON ser/de test would probably be most fair; most reflective of real world situations - my guess is that it'll still be a close call hah

**Comment by yoshuawuyts** [comment]
BUT this is all talking about perf. In the real world I'd happily lose a whole bunch of perf if stuff like composition and error handling is done well; and I think that's the truly added value of pull-streams.

It's good to know how much perf we're paying tho, that perhaps allows us to figure out ways to improve.

**Comment by ahdinosaur** [comment]
wow, thanks @yoshuawuyts, great to know that pull streams are in the same playground as node streams. :)

> BUT this is all talking about perf. In the real world I'd happily lose a whole bunch of perf if stuff like composition and error handling is done well; and I think that's the truly added value of pull-streams.

for sure, pull streams win. ;)

**Comment by dominictarr** [comment]
ah cool, this is interesting. Really, this is node's turf, node has been painstakingly optimized for this.
pull-steams have only been optimized for simplicity, so this just shows you how much simplicity gets you.

Doesn't this just wrap the node interface to http? this only shows that adding pull-stream slow nodestreams down very little. I bet we can do better than that, for example, here is a pull-stream version of `fs.createReadStream`.  https://github.com/DamonOehlman/pull-file/
there is a benchmark here, https://github.com/DamonOehlman/pull-file/tree/master/examples
which if you run it on a file, of say, 10 mb, then pull-file wins 95% of the time. The inflection point is about 1mb, where the pull stream is more likely to be faster. Oh, I have a spinning disk, one of you with a fancy SSD should run that test.

I bet you that if we rewrote the http module as pull streams, accessing `process.binding` directly, that we could beat node streams.

Also, compare a long chain of through streams, piping a bunch of things together each doing one little thing.

**Comment by yoshuawuyts** [comment]
@dominictarr I wonder if leveraging prototypes would provide a speed improvement; from my understanding, using closures creates a little bit of extra garbage on function creation compared to prototypes. Hugh said v8 really really really likes them; there's no need to use closures per-se, right?

> I bet you that if we rewrote the http module as pull streams, accessing process.binding directly, that we could beat node streams.

Hell yes! That would be so worth it.

**Comment by dominictarr** [comment]
Maybe, but there is just so little code in pull-streams that there isn't
much to optimise. Still it would be interesting to try. We certainly need a
comprehensive benchmark of pull vs node streams

**Comment by yoshuawuyts** [comment]
I've created a flame graph bench for `playground-pull-stream` using `0x`; as suspected it appears v8 isn't optimizing `pull-stream`s
- [flamegraph.html](https://gist.github.com/yoshuawuyts/08f0e1e09878e5294c9d)
- [0x](https://github.com/davidmarkclements/0x)

**Comment by dominictarr** [comment]
prehaps ironically, the flamegraph is really sluggish on my computer. how do you tell it's not optimized? I see the + optimized button, etc, but it's too sluggish to really see what is going on.

**Comment by yoshuawuyts** [comment]
yeah, it's super slow on my machine too - but pressing the + optimized button changes the colors on the graph. Guess I'm just privileged to have a relatively new macbook :(

**Comment by ahdinosaur** [comment]
hmm. well here's my understanding of one reason why or why not some javascript would be optimized: ["What's up with monomorphism?"](http://mrale.ph/blog/2015/01/11/whats-up-with-monomorphism.html). i wonder if pull streams are _always_ unoptimized (perhaps by nature of closures) or if it only applies to this use case (perhaps by nature of different "types" of arguments being passed in).

**Comment by dominictarr** [comment]
closures are just objects. you could make a transpiler that took, say, some reasonable patterns in writing closure based code and transpiled it to object based code, or whatever browsers are optimizing for this year.

**Comment by ahdinosaur** [comment]
@dominictarr yeah, i'm actually not too fussed about pull stream performance anymore, i'd rather keep it simple than change for the sake of performance (which might be browser-specific).
